// ─── מפת תוכן הבוט — נוצר אוטומטית מ-flows.ts (07/2026) ──────────────────────
// זהו התוכן האמיתי שהבוט שולח. מקור האמת: src/lib/bot/flows.ts + admin-flow.ts.
// לעדכון: לחלץ מחדש מהקוד (הקובץ נוצר ע"י Claude, לא לערוך ידנית בלי סנכרון).

export interface BotFlowStep {
  order: number
  stepId: string
  title: string
  userInput?: string
  botMessage: string
  branches?: string
  mode: 'FP' | 'LLM' | 'ידני'
  sideEffects?: string
}

export interface BotFlow {
  flowId: string
  title: string
  emoji: string
  entry: string
  steps: BotFlowStep[]
}

export const BOT_FLOW_MAP: BotFlow[] = [
  {
    flowId: "welcome_menu",
    title: "כניסה ובחירת מסלול",
    emoji: "👋",
    entry: "הודעה ראשונה / לא מזוהה כוונה",
    steps: [
      {
        order: 1,
        stepId: "welcome_start",
        title: "1 — רישום לצהרון",
        userInput: "בחירה מהתפריט (1-6) או שאלה חופשית",
        botMessage: "*1* — רישום לצהרון\n*2* — רישום לקייטנה\n*3* — ביטול\n*4* — שעות ולוח זמנים\n*5* — תשלומים\n*6* — איסוף מוקדם",
        branches: "בחירה מנתבת ללא וקט עתידי",
        mode: "FP",
        sideEffects: "session.currentFlow נקבע",
      },
    ],
  },
  {
    flowId: "registration_tzaharon",
    title: "רישום לצהרון",
    emoji: "🎒",
    entry: "כוונה: רישום_צהרון או בחירה: '1'",
    steps: [
      {
        order: 1,
        stepId: "register_start",
        title: "אם הטלפון מזוהה — הצגת רישומים קיימים; אחר…",
        userInput: "לא צריך קלט — בדיקה אוטומטית",
        botMessage: "אם הטלפון מזוהה — הצגת רישומים קיימים; אחרת: בחירת אזור",
        branches: "אם יש רישום קיים → register_existing_parent | אחרת → register_area",
        mode: "FP",
        sideEffects: "טעינת נתוני הורה מטלפון",
      },
      {
        order: 1.5,
        stepId: "register_complete_placeholder",
        title: "רואה שיש תשלום פעיל בשמך, אבל חסר שם הילד.…",
        userInput: "שם פרטי + משפחה של ילד",
        botMessage: "רואה שיש תשלום פעיל בשמך, אבל חסר שם הילד. מה שם הילד/ה? (שם פרטי + שם משפחה)",
        branches: "אם שם תקין → לשמור בDB ו-register_existing_parent",
        mode: "FP",
        sideEffects: "עדכון שם ילד בDB",
      },
      {
        order: 2,
        stepId: "register_existing_parent",
        title: "ראיתי שיש לכם כבר רישום אצלנו. במה אפשר לע…",
        userInput: "בחירה 1-4: רישום נוסף / עדכון / סטטוס / שאלה",
        botMessage: "ראיתי שיש לכם כבר רישום אצלנו. *במה אפשר לעזור?* *1* — לרשום ילד/ה נוסף/ת | *2* — לעדכן פרטים | *3* — לבדוק סטטוס תשלום | *4* — שאלה אחרת",
        branches: "1 → register_area | 2 → register_update_details (task) | 3 → payment_status_menu | 4 → register_existing_question (task)",
        mode: "FP",
        sideEffects: "ניתוב לפי בחירה",
      },
      {
        order: 3,
        stepId: "register_area",
        title: "לאיזה אזור מבקשים רישום לצהרון? 1 — דרום ה…",
        userInput: "בחירה 1-3: אזור",
        botMessage: "*לאיזה אזור מבקשים רישום לצהרון?* *1* — דרום השרון / חוף השרון | *2* — חוף הכרמל | *3* — גני ילדים תל אביב",
        branches: "בחירה תקינה → register_child_name",
        mode: "FP",
        sideEffects: "session.collectedData.area_code",
      },
      {
        order: 4,
        stepId: "register_child_name",
        title: "מה שם הילד/ה? (שם פרטי + שם משפחה)",
        userInput: "שם פרטי + משפחה של ילד",
        botMessage: "*מה שם הילד/ה?* (שם פרטי + שם משפחה)",
        branches: "בדיקה אם ילד כבר רשום → register_existing_parent | אחרת → register_class",
        mode: "FP",
        sideEffects: "session.collectedData.child_name | וידוא לפי looksLikeChildName()",
      },
      {
        order: 5,
        stepId: "register_class",
        title: "באיזו כיתה לומד/ת {שם}? (לדוגמה: א׳, ב׳, ג…",
        userInput: "כיתה או גיל (למשל: א׳, ב׳, גן חובה)",
        botMessage: "*באיזו כיתה לומד/ת {שם}?* (לדוגמה: א׳, ב׳, גן חובה)",
        branches: "בדיקת קיבולת | אם יש מקום → קישור טופס | אחרת → register_waiting_confirm",
        mode: "FP",
        sideEffects: "task יצור לנציגה | קישור טופס דינמי",
      },
      {
        order: 6,
        stepId: "register_waiting_confirm",
        title: "אין מקום פנוי לצהרון ב{אזור} אבל אפשר להצט…",
        userInput: "כן / לא",
        botMessage: "*אין מקום פנוי* לצהרון ב{אזור} אבל אפשר להצטרף לרשימת ההמתנה. *להצטרף?* (כן / לא)",
        branches: "כן → שמור לDB | לא → סיום",
        mode: "FP",
        sideEffects: "רישום לרשימת המתנה | task ליצור",
      },
    ],
  },
  {
    flowId: "camp_registration",
    title: "רישום לקייטנה",
    emoji: "🏕️",
    entry: "כוונה: רישום_קייטנה או בחירה: '2'",
    steps: [
      {
        order: 1,
        stepId: "camp_menu",
        title: "🏕️ קייטנות Kids & Fun! מה תרצו? 1 — לרשום …",
        userInput: "בחירה 1-3",
        botMessage: "*🏕️ קייטנות Kids & Fun!* *מה תרצו?* *1* — לרשום ילד/ה לקייטנה | *2* — לבדוק אם כבר נרשמתי | *3* — יש לי בעיה בהרשמה",
        branches: "1 → קישור לחנות | 2 → camp_check_name | 3 → camp_problem_desc",
        mode: "FP",
        sideEffects: "session.currentFlow",
      },
      {
        order: 2,
        stepId: "camp_check_name",
        title: "מה שם הילד/ה?",
        userInput: "שם ילד/ה",
        botMessage: "*מה שם הילד/ה?*",
        branches: "→ camp_check_id",
        mode: "FP",
        sideEffects: "session.collectedData.child_name",
      },
      {
        order: 3,
        stepId: "camp_check_id",
        title: "{שם} — מספר תעודת זהות של הילד/ה? (3-4 ספר…",
        userInput: "מספר תעודת זהות (3-4 ספרות אחרונות)",
        botMessage: "*{שם} — מספר תעודת זהות של הילד/ה?* (3-4 ספרות אחרונות מספיקות)",
        branches: "בדיקה אימות זהות | אם אומת ויש רישום → הצגת סטטוס | אחרת → task לנציגה",
        mode: "FP",
        sideEffects: "חיפוש child לפי שם וגם וידוא ת\"ז",
      },
      {
        order: 4,
        stepId: "camp_problem_desc",
        title: "אוי, כמה מבאס 😔 מה בדיוק קרה? תפרטו ונעזור…",
        userInput: "תיאור הבעיה",
        botMessage: "*אוי, כמה מבאס 😔* *מה בדיוק קרה?* תפרטו ונעזור!",
        branches: "→ task לנציגה | סיום",
        mode: "FP",
        sideEffects: "task יצור עם התיאור",
      },
    ],
  },
  {
    flowId: "camp_late",
    title: "רישום לקייטנה אחרי סגירת המועד",
    emoji: "⏰",
    entry: "כניסה דרך handler כאשר מעבר ממסלול קיימת",
    steps: [
      {
        order: 1,
        stepId: "camp_late_name",
        title: "מה שם הילד/ה?",
        userInput: "שם ילד/ה",
        botMessage: "*מה שם הילד/ה?*",
        branches: "→ camp_late_class",
        mode: "FP",
        sideEffects: "session.collectedData.child_name",
      },
      {
        order: 2,
        stepId: "camp_late_class",
        title: "{שם} — כיתה/גיל?",
        userInput: "כיתה / גיל",
        botMessage: "*{שם} — כיתה/גיל?*",
        branches: "→ task יצור | סיום",
        mode: "FP",
        sideEffects: "task בעדיפות גבוהה לנציגה",
      },
    ],
  },
  {
    flowId: "cancellation",
    title: "ביטול רישום לצהרון",
    emoji: "❌",
    entry: "כוונה: ביטול או בחירה: '3'",
    steps: [
      {
        order: 1,
        stepId: "cancel_start",
        title: "📋 מדיניות ביטולים — Kids & Fun • ביטול עד …",
        userInput: "לא צריך קלט",
        botMessage: "*📋 מדיניות ביטולים — Kids & Fun* • ביטול *עד ה-15 לחודש* — המשך עד סוף החודש + זיכוי מלא • ביטול *אחרי ה-15 לחודש* — ממשיכים חודש נוסף, ניתן להפסיק מהחודש שלאחריו. כדי להמשיך — *מה שם הילד/ה* שתרצו לבטל?",
        branches: "→ cancel_child",
        mode: "FP",
        sideEffects: "בדיקת יום בחודש (dayOfMonth)",
      },
      {
        order: 2,
        stepId: "cancel_child",
        title: "מה שם הילד/ה שתרצו לבטל?",
        userInput: "שם פרטי + משפחה של ילד",
        botMessage: "*מה שם הילד/ה* שתרצו לבטל?",
        branches: "בדיקת תאריך ביטול | אם לפני ה-15 → cancel_confirm_before15 | אחרת → cancel_confirm_after15",
        mode: "FP",
        sideEffects: "session.collectedData.child_name",
      },
      {
        order: 3,
        stepId: "cancel_confirm_before15",
        title: "📅 היום ה-{יום} לחודש — אתם בתוך חלון הביטו…",
        userInput: "כן / לא",
        botMessage: "*📅 היום ה-{יום} לחודש — אתם *בתוך חלון הביטול* ✅* {שם} יכול/ה להמשיך עד סוף החודש הנוכחי. תקבלו זיכוי מלא לחודש הבא. *לאשר את הביטול?* (כן / לא)",
        branches: "כן → ביצוע ביטול + ביטול הוראת קבע אם קיימת | לא → סיום",
        mode: "FP",
        sideEffects: "עדכון registrations status='בוטל' | ביטול הוראת קבע ב-PayPlus אוטומטית",
      },
      {
        order: 4,
        stepId: "cancel_confirm_after15",
        title: "📅 היום ה-{יום} לחודש. לפי תקנון הצהרון, בי…",
        userInput: "כן / לא / בקשת חריג",
        botMessage: "*📅 היום ה-{יום} לחודש.* לפי תקנון הצהרון, ביטול לאחרי ה-15 — *ממשיכים חודש נוסף* ומפסיקים מהחודש שלאחריו. *לאשר?* (כן / לא) אם יש נסיבות מיוחדות — כתבו ואנחנו נבדוק",
        branches: "כן → ביצוע ביטול | לא → ביטול הביטול | חריג (כמו מחלה) → task לנציגה",
        mode: "FP",
        sideEffects: "עדכון registration + task לנציגה",
      },
    ],
  },
  {
    flowId: "schedule_and_hours",
    title: "שעות, לוח זמנים וחגים",
    emoji: "📅",
    entry: "כוונה: שאלת_לוז או בחירה: '4'",
    steps: [
      {
        order: 1,
        stepId: "schedule_query",
        title: "חיפוש ב-FAQ לפי fuzzy match או לפי נושא",
        userInput: "שאלה על שעות / חגים / חופש",
        botMessage: "חיפוש ב-FAQ לפי fuzzy match או לפי נושא",
        branches: "אם נמצא FAQ → תשובה מהFAQ | אחרת → תשובה רכה כללית",
        mode: "LLM",
        sideEffects: "חיפוש ב-faqs table",
      },
    ],
  },
  {
    flowId: "payment_setup",
    title: "הסדרת תשלום",
    emoji: "🏦",
    entry: "כוונה: אפשרויות_תשלום או בחירה מ-payment_status_menu או מהצעת מקום מרשימה",
    steps: [
      {
        order: 1,
        stepId: "payment_setup_start / payment_setup_offer",
        title: "הסדרת תשלום — הצעת הוראת קבע (ראשי, §10-11)",
        userInput: "כן / אפשרות אחרת / שיטה",
        botMessage: "מציעים *הוראת קבע* ישירות (לא תפריט 6 שיטות): *להסדיר הוראת קבע?* (כן / אפשרות אחרת). חלופות רק אחרי סירוב.",
        branches: "אישור הו\"ק → payment_setup_child_name | סירוב/חלופות → payment_setup_method (תפריט השיטות)",
        mode: "FP",
        sideEffects: "loadParentRegistrationContext() אם צריך | payment_method='standing_order' באישור",
      },
      {
        order: 2,
        stepId: "payment_setup_child_name",
        title: "לפני שאשלח את הקישור, לצורך זיהוי: מה שם ה…",
        userInput: "שם ילד/ה מלא",
        botMessage: "*לפני שאשלח את הקישור, לצורך זיהוי:* *מה שם הילד/ה? (שם פרטי + שם משפחה)*",
        branches: "→ payment_setup_area",
        mode: "FP",
        sideEffects: "session.collectedData.child_name",
      },
      {
        order: 3,
        stepId: "payment_setup_area",
        title: "באיזה אזור {שם} בצהרון? 1 — כרמל (עתלית וה…",
        userInput: "בחירה 1-3: אזור",
        botMessage: "*באיזה אזור {שם} בצהרון?* *1* — כרמל (עתלית והסביבה) | *2* — שרון (רשפון, מתן) | *3* — תל אביב",
        branches: "→ resolvePaymentSchool() (מסגרת לתמחור)",
        mode: "FP",
        sideEffects: "session.collectedData.area_code + area_label",
      },
      {
        order: 4,
        stepId: "payment_setup_school",
        title: "ובאיזה גן / בית ספר? רשימה דינמית מתוך sch…",
        userInput: "בחירה 1-N: בחירת גן/בית ספר",
        botMessage: "*ובאיזה גן / בית ספר?* רשימה דינמית מתוך schools table",
        branches: "→ paymentResolveFeeAndContinue() (תמחור)",
        mode: "FP",
        sideEffects: "session.collectedData.child_school | הוצאת המחיר",
      },
      {
        order: 5,
        stepId: "payment_setup_class",
        title: "ובאיזו כיתה {שם}? (למשל: א / ב / ג)",
        userInput: "כיתה",
        botMessage: "*ובאיזו כיתה {שם}?* (למשל: א / ב / ג)",
        branches: "→ paymentResolveFeeAndContinue() (תמחור לפי כיתה)",
        mode: "FP",
        sideEffects: "session.collectedData.child_class",
      },
      {
        order: 6,
        stepId: "payment_setup_checks",
        title: "📝 צ׳קים — מצוין! כמה צ׳קים תרצו לתת? (למשל…",
        userInput: "מספר צ׳קים (1-12)",
        botMessage: "*📝 צ׳קים — מצוין!* *כמה צ׳קים תרצו לתת?* (למשל: 3, 6, 10)",
        branches: "תשובה עם פרטים והנחיות + task לנציגה",
        mode: "FP",
        sideEffects: "task לתיאום קבלת צ׳קים",
      },
    ],
  },
  {
    flowId: "payment_status",
    title: "בדיקת סטטוס תשלום",
    emoji: "💳",
    entry: "כוונה: בדיקת_תשלום או בחירה '5' או בחירה '3' מ-register_existing_parent",
    steps: [
      {
        order: 1,
        stepId: "payment_status_menu",
        title: "💰 תשלומים — Kids & Fun על מה תרצו לשאול? 1…",
        userInput: "בחירה 1-5",
        botMessage: "*💰 תשלומים — Kids & Fun* על מה תרצו לשאול? *1* — סטטוס התשלום שלי | *2* — לשנות שיטת תשלום | *3* — לא עבר תשלום / בעיה | *4* — מה העלות החודשית? | *5* — 💳 להסדיר תשלום חדש",
        branches: "1 → getPaymentStatusByPhone() או payment_status_child_name אם לא מזוהה | 2 → payment_setup_method | 3 → payment_fail_start | 4 → cost_info_start | 5 → payment_setup_start",
        mode: "FP",
        sideEffects: "session.currentFlow",
      },
      {
        order: 2,
        stepId: "payment_status_child_name",
        title: "🔍 בדיקת סטטוס תשלום לא מצאתי את המספר שלך …",
        userInput: "שם ילד/ה מלא",
        botMessage: "*🔍 בדיקת סטטוס תשלום* לא מצאתי את המספר שלך במערכת — בוא/י נזהה אותך: *מה שם הילד/ה? (שם פרטי + שם משפחה)*",
        branches: "getPaymentStatusByChildName() | אם לא נמצא → task לנציגה",
        mode: "FP",
        sideEffects: "חיפוש לפי שם",
      },
    ],
  },
  {
    flowId: "cost_info",
    title: "שאלות על עלויות",
    emoji: "💰",
    entry: "בחירה '4' מ-payment_status_menu או כוונה בדיוקית",
    steps: [
      {
        order: 1,
        stepId: "cost_info_start",
        title: "💰 שאלות עלות — Kids & Fun על מה תרצו לדעת?…",
        userInput: "בחירה 1-4",
        botMessage: "*💰 שאלות עלות — Kids & Fun* על מה תרצו לדעת? *1* — 📅 עלות חודשית צהרון | *2* — ☀️ תשלום מראש לקייטנה | *3* — 👨‍👩‍👧‍👦 הנחת אחים / אחיות | *4* — 💬 שאלה אחרת על עלות",
        branches: "1 → תשובה קבועה | 2 → תשובה קבועה | 3 → תשובה קבועה | 4 → cost_info_freetext",
        mode: "FP",
        sideEffects: "none",
      },
      {
        order: 2,
        stepId: "cost_info_freetext",
        title: "💬 שאלות נוספות על עלות כתבו את שאלתכם בחופ…",
        userInput: "שאלה חופשית",
        botMessage: "*💬 שאלות נוספות על עלות* כתבו את שאלתכם בחופשיות — אנסה לענות! 😊",
        branches: "→ LLM fallback",
        mode: "LLM",
        sideEffects: "none",
      },
    ],
  },
  {
    flowId: "payment_failure",
    title: "טיפול בכשל תשלום",
    emoji: "🔴",
    entry: "כוונה: כשל_תשלום או בחירה '3' מ-payment_status_menu",
    steps: [
      {
        order: 1,
        stepId: "payment_fail_start",
        title: "היי {שם}! 😊 שם לב שהיתה בעיה בתשלום — אין …",
        userInput: "בחירה 1-5",
        botMessage: "*היי {שם}! 😊* שם לב שהיתה בעיה בתשלום — אין מה לדאוג, מטפלים ביחד 💛 *מה המצב?* *1* — החלפתי כרטיס, יש לי פרטים חדשים | *2* — רוצה לעבור לאמצעי תשלום אחר | *3* — רוצה לשנות את תאריך החיוב | *4* — עוד לא מסודר, תחזרו אלי בעוד כמה ימים | *5* — אחר",
        branches: "בחירה 1-4 → payment_fail_child_name (זיהוי כפול) | בחירה 5 → payment_fail_describe (task לנציגה)",
        mode: "FP",
        sideEffects: "session.collectedData.payment_fail_branch",
      },
      {
        order: 2,
        stepId: "payment_fail_child_name",
        title: "לפני שנמשיך, לזיהוי: מה שם הילד/ה? (שם פרט…",
        userInput: "שם ילד/ה מלא",
        botMessage: "*לפני שנמשיך, לזיהוי:* *מה שם הילד/ה? (שם פרטי + שם משפחה)*",
        branches: "→ routePaymentFailBranch()",
        mode: "FP",
        sideEffects: "session.collectedData.child_name",
      },
      {
        order: 3,
        stepId: "payment_fail_card_link_sent",
        title: "כשתסיימי את התשלום בקישור — הוראת הקבע היש…",
        userInput: "שום דבר / שאלה נוספת",
        botMessage: "*כשתסיימי את התשלום בקישור* — הוראת הקבע הישנה תבוטל אוטומטית 💛",
        branches: "סיום",
        mode: "FP",
        sideEffects: "none",
      },
      {
        order: 4,
        stepId: "payment_fail_method_choice",
        title: "באיזה אמצעי תשלום תרצי להמשיך? 1 — 🏦 הוראת…",
        userInput: "בחירה 1-5: אמצעי תשלום חדש",
        botMessage: "*באיזה אמצעי תשלום תרצי להמשיך?* *1* — 🏦 הוראת קבע (אשראי) | *2* — 💳 כרטיס אשראי חודשי | *3* — 💵 מזומן | *4* — 📝 צ׳קים | *5* — 🏛️ העברה בנקאית",
        branches: "בחירה חדשה ניתוב לתשובה מתאימה",
        mode: "FP",
        sideEffects: "הנחיות תשלום או task לנציגה",
      },
      {
        order: 5,
        stepId: "payment_fail_new_date",
        title: "בטח! באיזה יום בחודש יתאים לך החיוב? (1-28…",
        userInput: "יום בחודש (1-28)",
        botMessage: "*בטח!* *באיזה יום בחודש* יתאים לך החיוב? (1-28)",
        branches: "בדיקת תקינות | עדכון ב-PayPlus API",
        mode: "FP",
        sideEffects: "updateRecurringBillingDate() ב-PayPlus",
      },
      {
        order: 6,
        stepId: "payment_fail_remind_when",
        title: "בסדר גמור 😊 מתי לחזור אליך? (לדוגמה: עוד 3…",
        userInput: "תאריך טקסט חופשי (למשל: עוד 3 ימים)",
        botMessage: "*בסדר גמור 😊* *מתי לחזור אליך?* (לדוגמה: עוד 3 ימים, ב-25 לחודש, בעוד שבוע)",
        branches: "parseRemindWhen() | שמור ב-followup_reminders + task",
        mode: "FP",
        sideEffects: "תזכורת אוטומטית ב-DB",
      },
      {
        order: 7,
        stepId: "payment_fail_describe",
        title: "מבינים 💛 ספר/י לי מה קורה ואנחנו נמצא פתרו…",
        userInput: "תיאור חופשי של הבעיה",
        botMessage: "*מבינים 💛* ספר/י לי מה קורה ואנחנו נמצא פתרון ביחד",
        branches: "→ task לנציגה",
        mode: "FP",
        sideEffects: "task בעדיפות דחוף",
      },
    ],
  },
  {
    flowId: "waiting_list_spot",
    title: "הצעת מקום מרשימת המתנה",
    emoji: "⏳",
    entry: "מסלול יזום מהנציגה — המערכת שולחת הודעה וההורה מגיב",
    steps: [
      {
        order: 1,
        stepId: "waiting_spot_confirm",
        title: "🎉 מעולה! נפתח מקום עבור {שם} ב{אזור}! האם …",
        userInput: "כן / לא",
        botMessage: "*🎉 מעולה! נפתח מקום עבור {שם}* ב{אזור}! *האם אתם רוצים להמשיך?* (כן / לא)",
        branches: "כן → from_spot_offer=true ו-payment_setup_start | לא → task לנציגה ועבור למועמד הבא",
        mode: "FP",
        sideEffects: "session.collectedData.from_spot_offer",
      },
    ],
  },
  {
    flowId: "early_pickup",
    title: "בקשת איסוף מוקדם",
    emoji: "🚗",
    entry: "כוונה: איסוף_מוקדם או בחירה: '6'",
    steps: [
      {
        order: 1,
        stepId: "pickup_start",
        title: "👋 בקשת איסוף מוקדם מה שם הילד/ה שתרצו לאסו…",
        userInput: "לא צריך קלט",
        botMessage: "*👋 בקשת איסוף מוקדם* *מה שם הילד/ה* שתרצו לאסוף?",
        branches: "→ pickup_child",
        mode: "FP",
        sideEffects: "none",
      },
      {
        order: 2,
        stepId: "pickup_child",
        title: "{שם} — באיזו שעה תרצו לאסוף?",
        userInput: "שם ילד/ה",
        botMessage: "*{שם} — באיזו שעה* תרצו לאסוף?",
        branches: "→ pickup_time",
        mode: "FP",
        sideEffects: "session.collectedData.child_name",
      },
      {
        order: 3,
        stepId: "pickup_time",
        title: "שעה {שעה} ✅ מי יאסוף? (שם + קרבה, למשל: אב…",
        userInput: "שעה",
        botMessage: "*שעה {שעה} ✅* *מי יאסוף?* (שם + קרבה, למשל: אבא דני)",
        branches: "→ pickup_collector",
        mode: "FP",
        sideEffects: "session.collectedData.pickup_time",
      },
      {
        order: 4,
        stepId: "pickup_collector",
        title: "✅ בקשת האיסוף התקבלה! 👧 ילד/ה: {שם} | ⏰ שע…",
        userInput: "שם + קרבה של המאסף",
        botMessage: "*✅ בקשת האיסוף התקבלה!* 👧 ילד/ה: *{שם}* | ⏰ שעה: *{שעה}* | 🚗 אוסף/ת: *{שם}* | הצוות עודכן ויהיה מוכן 😊",
        branches: "→ סיום + task + notifyFramework",
        mode: "FP",
        sideEffects: "task יצור בעדיפות גבוהה | notifyFramework byChildName",
      },
    ],
  },
  {
    flowId: "llm_fallback",
    title: "LLM Fallback — Claude כשום FP לא עונה",
    emoji: "🤖",
    entry: "כשלי FP או בחירה לא ידועה",
    steps: [
      {
        order: 1,
        stepId: "llm_response",
        title: "תשובה מ-Claude עם הקשר השיחה וההודעות הקוד…",
        userInput: "כל קלט שלא זוהה",
        botMessage: "תשובה מ-Claude עם הקשר השיחה וההודעות הקודמות",
        branches: "אם Claude מציע מסלול (suggestFlow) → session.currentFlow = suggestFlow",
        mode: "LLM",
        sideEffects: "callLLMFallback() + אפשרי task לנציגה",
      },
    ],
  },
  {
    flowId: "media_handler",
    title: "טיפול בקבצים ותמונות",
    emoji: "📎",
    entry: "זיהוי קובץ / תמונה ממשתמש",
    steps: [
      {
        order: 1,
        stepId: "media_detection",
        title: "זיהוי סוג המדיה — ניתוח דינמי",
        userInput: "קובץ URL או תמונה",
        botMessage: "זיהוי סוג המדיה — ניתוח דינמי",
        branches: "→ handleMediaMessage()",
        mode: "FP",
        sideEffects: "תשובה או task לנציגה",
      },
    ],
  },
  {
    flowId: "admin_flow",
    title: "מסלול ניהול לנציגה",
    emoji: "👩‍💼",
    entry: "כתיבת 'ניהול' או 'אדמין' או 'תפריט ניהול' — רק לנציגה (קורלי)",
    steps: [
      {
        order: 1,
        stepId: "admin_menu",
        title: "👩‍💼 מסלול ניהול — Kids & Fun 1 — 📋 פניות פ…",
        userInput: "בחירה 1-5 או 'יציאה' או שאלה חופשית",
        botMessage: "*👩‍💼 מסלול ניהול — Kids & Fun* *1* — 📋 פניות פתוחות | *2* — 🔍 מצב הורה (טלפון או שם) | *3* — 📊 סיכום היום | *4* — 🔇 השתקת בוט לפונה | *5* — ▶️ החזרת בוט לפונה | *יציאה* — חזרה למצב הורה-בודקת 🧪",
        branches: "1 → admin_tasks (רשימת פניות) | 2 → admin_status_wait | 3 → סיכום | 4-5 → שתק/חזר | יציאה → חזרה למצב הורה",
        mode: "FP",
        sideEffects: "saveAdminState() ב-bot_sessions",
      },
      {
        order: 2,
        stepId: "admin_tasks",
        title: "👩‍💼 פניות פתוחות (עד 8) רשימה ממוינת לפי ע…",
        userInput: "בחירה 1-8 (מספר פנייה) או 'סגור N' או 'תפריט'",
        botMessage: "*👩‍💼 פניות פתוחות* (עד 8) רשימה ממוינת לפי עדיפות עם מספרים ודוט צבעוני (🔴 דחוף, 🟠 גבוה, 🔵 רגיל)",
        branches: "סגור N → סגירת פנייה | מספר בחר פנייה → פרטים | תפריט → admin_menu",
        mode: "FP",
        sideEffects: "עדכון tasks.status='טופל'",
      },
      {
        order: 3,
        stepId: "admin_status_wait",
        title: "👩‍💼 שלחי טלפון או שם של ההורה 🔍",
        userInput: "טלפון או שם הורה",
        botMessage: "*👩‍💼 שלחי טלפון או שם של ההורה 🔍*",
        branches: "חיפוש בDB | הצגת סטטוס הורה (ילדים, רישומים, תשלום, הוראת קבע, פניות)",
        mode: "FP",
        sideEffects: "אחזור נתונים מפרנטס, צילדרן, ריג'סטריישנס, פיימנטס",
      },
      {
        order: 4,
        stepId: "admin_llm_freetext",
        title: "שאלה מענה ב-Claude Haiku עם הקשר חי של המע…",
        userInput: "שאלה חופשית בעברית",
        botMessage: "שאלה מענה ב-Claude Haiku עם הקשר חי של המערכת",
        branches: "→ buildAdminContext() + adminLLM()",
        mode: "LLM",
        sideEffects: "קריאה ל-Claude API עם system prompt ונתוני המערכת החיים",
      },
      {
        order: 5,
        stepId: "admin_flash_commands",
        title: "פקודה בזק — עובדת מכל מצב",
        userInput: "'השתק 0541234567' או 'החזר 0541234567'",
        botMessage: "פקודה בזק — עובדת מכל מצב",
        branches: "השתק/החזר via uChat API",
        mode: "FP",
        sideEffects: "pauseBot() / resumeBot() ב-uChat",
      },
    ],
  },
]
